// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id             int64  `json:"id"`
	Name           string `json:"name"`
	Follow_count   int64  `json:"follow_count,optional"`
	Follower_count int64  `json:"follower_count,optional"`
	Is_follow      bool   `json:"is_follow"`
}

type Video struct {
	Id             int64  `json:"id"`
	Author         User   `json:"author"`
	Play_url       string `json:"play_url"`
	Cover_url      string `json:"cover_url"`
	Favorite_count int64  `json:"favorite_count"`
	Comment_count  int64  `json:"comment_count"`
	Is_favorite    bool   `json:"is_favorite"`
	Title          string `json:"title"`
}

type Comment struct {
	Id          int64  `json:"id"`
	User        User   `json:"user"`
	Content     string `json:"content"`
	Create_date string `json:"create_date"`
}

type Douyin_feed_request struct {
	Latest_time int64  `form:"latest_time,optional"`
	Token       string `form:"token,optional"`
}

type Douyin_feed_response struct {
	Status_code int32   `json:"status_code"`
	Status_msg  string  `json:"status_msg,optional"`
	Video_list  []Video `json:"video_list"`
	Next_time   int64   `json:"next_time,optional"`
}

type Douyin_user_register_request struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type Douyin_user_register_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
	User_id     int64  `json:"user_id"`
	Token       string `json:"token"`
}

type Douyin_user_login_request struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type Douyin_user_login_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
	User_id     int64  `json:"user_id"`
	Token       string `json:"token"`
}

type Douyin_user_request struct {
	User_id int64  `form:"user_id"`
	Token   string `form:"token"`
}

type Douyin_user_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
	User        User   `json:"user"`
}

type Douyin_publish_action_request struct {
	Token string `json:"token"`
	Data  []byte `json:"data"`
	Title string `json:"title"`
}

type Douyin_publish_action_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
}

type Douyin_publish_list_request struct {
	User_id int64 `form:"user_id"`
	//Token   string `form:"token"`
}

type Douyin_publish_list_response struct {
	Status_code int32   `json:"status_code"`
	Status_msg  string  `json:"status_msg,optional"`
	Video_list  []Video `json:"video_list"`
}

type Douyin_favorite_action_request struct {
	//User_id     int64  `form:"user_id"`
	Token       string `form:"token"`
	Video_id    int64  `form:"video_id"`
	Action_type int32  `form:"action_type"`
}

type Douyin_favorite_action_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
}

type Douyin_favorite_list_request struct {
	User_id int64  `form:"user_id"`
	//Token string `form:"token,"`
}

type Douyin_favorite_list_response struct {
	Status_code int32   `json:"status_code"`
	Status_msg  string  `json:"status_msg,optional"`
	Video_list  []Video `json:"video_list"`
}

type Douyin_comment_action_request struct {
	//User_id      int64  `form:"user_id"`
	Token        string `form:"token"`
	Video_id     int64  `form:"video_id"`
	Action_type  int32  `form:"action_type"`
	Comment_text string `form:"comment_text,optional"`
	Comment_id   int64  `form:"comment_id,optional"`
}

type Douyin_comment_action_response struct {
	Status_code int32   `json:"status_code"`
	Status_msg  string  `json:"status_msg,optional"`
	Comment     Comment `json:"comment,optional"`
}

type Douyin_comment_list_request struct {
	//User_id  int64  `form:"user_id"`
	Token    string `form:"token"`
	Video_id int64  `form:"video_id"`
}

type Douyin_comment_list_response struct {
	Status_code  int32     `json:"status_code"`
	Status_msg   string    `json:"status_msg,optional"`
	Comment_list []Comment `json:"comment_list"`
}

type Douyin_relation_action_request struct {
	//User_id     int64  `form:"user_id"`
	Token       string `form:"token"`
	To_user_id  int64  `form:"to_user_id"`
	Action_type int32  `form:"action_type"`
}

type Douyin_relation_action_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
}

type Douyin_relation_follow_list_request struct {
	User_id int64  `form:"user_id"`
	Token   string `form:"token"`
}

type Douyin_relation_follow_list_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
	User_list   []User `json:"user_list"`
}

type Douyin_relation_follower_list_request struct {
	User_id int64  `form:"user_id"`
	Token   string `form:"token"`
}

type Douyin_relation_follower_list_response struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg,optional"`
	User_list   []User `json:"user_list"`
}
